spring.application.name=patrimonio

spring.datasource.url=jdbc:postgresql://10.230.32.19:5060/cordierita
spring.datasource.username=enzo_damasceno
spring.datasource.password=7VrpDlfdAMCwKiOqq8q8WNtC

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=patrimonio_new

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB